Book.delete_all
Book.create!([
    {:title=>"Cooking", :authors=>["Whitecap Books"], :img_url=>"http://bks7.books.google.pl/books?id=l_HwDnSFbUAC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking", :authors=>["Lisa Feeney"], :img_url=>"http://bks9.books.google.pl/books?id=oAZqKdmmGJ8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking", :authors=>["James Peterson"], :img_url=>"http://bks3.books.google.pl/books?id=lRrZI9F9YEIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"On Food and Cooking", :authors=>["Harold McGee"], :img_url=>"http://bks4.books.google.pl/books?id=bKVCtH4AjwgC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"A History of Cooks and Cooking", :authors=>["Michael Symons"], :img_url=>"http://bks5.books.google.pl/books?id=DmEDa9wG6yUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking Lessons", :authors=>["Sherrie A. Inness"], :img_url=>"http://bks7.books.google.pl/books?id=qM2hnC9iMYEC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking", :authors=>["Hervé This", "Pierre Gagnaire"], :img_url=>"http://bks8.books.google.pl/books?id=ZHD7X08RCUwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Study Guide to Accompany Professional Cooking", :authors=>["Wayne Gisslen", "Mary Ellen Griffin"], :img_url=>"http://bks6.books.google.pl/books?id=e221uiNiknoC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Professional Cooking for Canadian Chefs", :authors=>["Wayne Gisslen", "Mary Ellen Griffin", "Le Cordon Bleu"], :img_url=>"http://bks6.books.google.pl/books?id=EzSwCGBHr3YC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking for Geeks", :authors=>["Jeff Potter"], :img_url=>"http://bks8.books.google.pl/books?id=IQ3PJY7zs6EC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Indian Cooking", :authors=>["Jan Purser", "Ajoy Joshi"], :img_url=>"http://bks4.books.google.pl/books?id=0hqtvnDLL1IC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Joy of Cooking", :authors=>["Irma von Starkloff Rombauer", "Marion Rombauer Becker", "Ethan Becker"], :img_url=>"http://bks7.books.google.pl/books?id=dlOIUX55ROMC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Essentials of Classic Italian Cooking", :authors=>["Marcella Hazan"], :img_url=>"http://bks2.books.google.pl/books?id=1FVLv7WS4C4C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Best Of Chinese Cooking", :authors=>["Sanjeev Kapoor"], :img_url=>"http://bks4.books.google.pl/books?id=sUzAqG7YxrUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"India Food and Cooking", :authors=>["Pat Chapman"], :img_url=>"http://bks7.books.google.pl/books?id=orHWFRMKf4EC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Professional Cooking, College Version", :authors=>["Wayne Gisslen"], :img_url=>"http://bks6.books.google.pl/books?id=N5el9CYbEP0C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Ayurvedic Cooking for Westerners", :authors=>["Amadea Morningstar"], :img_url=>"http://bks9.books.google.pl/books?id=MOioBDj__o8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Cooking of History", :authors=>["Stephan Palmié"], :img_url=>"http://bks9.books.google.pl/books?id=Y4MYGfvqpbsC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Art of Cooking", :authors=>["Maestro Martino of Como", "Luigi Ballerini"], :img_url=>"http://bks5.books.google.pl/books?id=9Efw2S_NekYC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"New Indian Home Cooking", :authors=>["Madhu Gadia"], :img_url=>"http://bks7.books.google.pl/books?id=mY3cO8b5iToC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Science of Cooking", :authors=>["Peter Barham"], :img_url=>"http://bks3.books.google.pl/books?id=oGq4v4e7rG8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Prashad Cooking with Indian Masters", :authors=>["J. Inder Singh Kalra", "Pradeep Das Gupta"], :img_url=>"http://bks2.books.google.pl/books?id=-UFwsluKqM8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Microwave Cooking Made Easy", :authors=>["Sanjeev Kapoor"], :img_url=>"http://bks9.books.google.pl/books?id=OMloK11Mny8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Fine Cooking Cookies", :authors=>["Fine Cooking Magazine"], :img_url=>"http://bks3.books.google.pl/books?id=TU-jmiPEosUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Taiwanese Home Style Cooking: A Guide to Taiwanese Cooking", :authors=>["North American Taiwanese Women's Association. Northern California Chapter"], :img_url=>"http://bks6.books.google.pl/books?id=t3tjwAw4nVgC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Traditional South African Cooking", :authors=>["Magdaleen Van Wyk", "Pat Barton"], :img_url=>"http://bks1.books.google.pl/books?id=abmTKV1E-TwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Healthy Cooking for Two (or Just You)", :authors=>["Frances Price"], :img_url=>"http://bks9.books.google.pl/books?id=zbLGPFXMYhIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking by the Book", :authors=>["Mary Anne Schofield"], :img_url=>"http://bks0.books.google.pl/books?id=zvOppQPQxPgC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Kids Cooking Without a Stove", :authors=>["Aileen Paul"], :img_url=>"http://bks0.books.google.pl/books?id=EfC6j3xLKbQC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Southern Cooking", :authors=>["S. R. Dull"], :img_url=>"http://bks4.books.google.pl/books?id=sabe3fbY-VkC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"What Mrs. Fisher Knows about Old Southern Cooking", :authors=>["Mrs. Fisher"], :img_url=>"http://bks3.books.google.pl/books?id=WlFaENz0YHwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Sanjeev Kapoor's No-oil Vegetarian Cooking", :authors=>["Sanjeev Kapoor", "Alyona Kapoor"], :img_url=>"http://bks1.books.google.pl/books?id=KUqxOLaF3z4C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The New Cleaning & Cooking Fish", :authors=>["Slyvia Gashline"], :img_url=>"http://bks5.books.google.pl/books?id=HHBfJNfDSN0C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Freezer Bag Cooking: Trail Food Made Simple", :authors=>["Sarah Svien", "Sarah Svien Kirkconnell"], :img_url=>"http://bks1.books.google.pl/books?id=oTlQdlTVNS8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Texas Home Cooking", :authors=>["Cheryl Alters Jamison", "Bill Jamison"], :img_url=>"http://bks3.books.google.pl/books?id=nKtVIw8cXX8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Folk Art of Japanese Country Cooking", :authors=>["Gaku Homma"], :img_url=>"http://bks0.books.google.pl/books?id=HZRDsVUZufoC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with Cannabis", :authors=>["Adam Gottlieb"], :img_url=>"http://bks5.books.google.pl/books?id=TuLhmcyJ7P8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The", :authors=>["Gil Marks"], :img_url=>"http://bks4.books.google.pl/books?id=Ux2lGKCKVPYC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking, Eating, Thinking", :authors=>["Deane W. Curtin", "Lisa Maree Heldke"], :img_url=>"http://bks6.books.google.pl/books?id=Hq9dT_iH8xsC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Storybook Stew", :authors=>["Suzanne I. Barchers", "Peter J. Rauen"], :img_url=>"http://bks7.books.google.pl/books?id=itfMvU6teL4C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"NOLS Backcountry Cooking", :authors=>["National Outdoor Leadership School (U.S.)"], :img_url=>"http://bks9.books.google.pl/books?id=gdaSj64ls5UC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Joy of Cooking", :authors=>["Irma S. Rombauer", "Marion Rombauer Becker"], :img_url=>"http://bks9.books.google.pl/books?id=C4_5MCUd6ucC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"A Blokes Guide to Cooking the Ultimate Bluffers Guide", :authors=>["Lambert Rowst"], :img_url=>"http://bks4.books.google.pl/books?id=i8LBrYJsmu4C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Regional Greek Cooking", :authors=>["Dean Karayanis", "Catherine Karayanis"], :img_url=>"http://bks9.books.google.pl/books?id=NrIapgM4LwQC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Authentic Vietnamese Cooking", :authors=>["Corinne Trang"], :img_url=>"http://bks3.books.google.pl/books?id=1KPlqAmRcbYC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Secrets of Colombian Cooking", :authors=>["Patricia McCausland-Gallo"], :img_url=>"http://bks5.books.google.pl/books?id=JqxNgWs6qSwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Home Book of Smoke Cooking", :authors=>["Jack Sleight", "Raymond Hull"], :img_url=>"http://bks5.books.google.pl/books?id=J1mZL49w1ywC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Joy of Cooking: All About Cookies", :authors=>["Irma S. Rombauer", "Marion Rombauer Becker", "Ethan Becker"], :img_url=>"http://bks3.books.google.pl/books?id=mAXZr6PnGcwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Boston Cooking School Cook Book", :authors=>["Mary Johnson Lincoln"], :img_url=>"http://bks9.books.google.pl/books?id=ZpY17mjFHywC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Royal Hyderabadi Cooking", :authors=>["Sanjeev Kapoor and Harpal Singh Sokhi"], :img_url=>"http://bks9.books.google.pl/books?id=NNI4LbcEbrYC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Book of Japanese Cooking", :authors=>["Emi Kazuko"], :img_url=>"http://bks4.books.google.pl/books?id=JAb2qBcnSLAC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Dressing and Cooking Wild Game", :authors=>["Complete Hunter Creative Publishing international Teresa Marrone", "Creative Publishing Editors"], :img_url=>"http://bks3.books.google.pl/books?id=uHRsuM_HkE4C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking For The Family", :authors=>["Jeroo Mehta"], :img_url=>"http://bks9.books.google.pl/books?id=tqgGZ7IEGJ8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"German Cooking", :authors=>["Marianna Olszewska Heberle"], :img_url=>"http://bks5.books.google.pl/books?id=yiF0voEEaF8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Healthy Homestyle Cooking", :authors=>["Evelyn Tribole"], :img_url=>"http://bks3.books.google.pl/books?id=QN3U2LhvGFQC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Icons of American Cooking", :authors=>["Victor William Geraci", "Elizabeth S. Demers"], :img_url=>"http://bks3.books.google.pl/books?id=kcwcIuRury0C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"A Korean Mother's Cooking Notes", :authors=>["S?n-yong Chang"], :img_url=>"http://bks2.books.google.pl/books?id=0vuzx3jolAcC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking Wizardry for Kids", :authors=>["Margaret Kenda"], :img_url=>"http://bks7.books.google.pl/books?id=4__AP5dGTtMC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Big Buy Cooking", :authors=>["Fine Cooking"], :img_url=>"http://bks0.books.google.pl/books?id=Vh9WdMyjlAUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with Johnny Vee", :authors=>["John Vollertsen"], :img_url=>"http://bks8.books.google.pl/books?id=elPvymYXwfsC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Enlitened Kosher Cooking", :authors=>["Nechama Cohen"], :img_url=>"http://bks8.books.google.pl/books?id=EEqgZ04-Zb4C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Prairie Home Cooking", :authors=>["Judith M. Fertig"], :img_url=>"http://bks7.books.google.pl/books?id=eEMyNDQP4VEC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Fine Cooking Appetizers", :authors=>["Fine Cooking Magazine"], :img_url=>"http://bks5.books.google.pl/books?id=PwiEgJ0PfOQC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Fine Cooking in Season", :authors=>["Editors of Fine Cooking"], :img_url=>"http://bks6.books.google.pl/books?id=eAyNxv2I1LoC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Japanese Cooking", :authors=>["Shizuo Tsuji"], :img_url=>"http://bks5.books.google.pl/books?id=fby2Er0seMMC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Classic Russian Cooking", :authors=>["Elena Molokhovets"], :img_url=>"http://bks7.books.google.pl/books?id=ttlCGJxfLRUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Sanjeev Kapoor's No-oil Cooking", :authors=>["Sanjeev Kapoor", "Alyona Kapoor"], :img_url=>"http://bks3.books.google.pl/books?id=F683gKF2UScC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking the Israeli Way", :authors=>["Josephine Bacon"], :img_url=>"http://bks5.books.google.pl/books?id=Nbvi4Zye0DgC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Microwave Magic - The Art of 21st Century Cooking", :authors=>["Jennipher Marshall-Jenkinson"], :img_url=>"http://bks6.books.google.pl/books?id=msOmnLpFmacC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Practice of Everyday Life", :authors=>["Michel de Certeau"], :img_url=>"http://bks4.books.google.pl/books?id=NHJNScWvV70C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Caribbean Cooking", :authors=>["John DeMers"], :img_url=>"http://bks7.books.google.pl/books?id=h229TouniGIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with Swami Yogananda: Holiday Recipes", :authors=>["Yogananda (Paramahansa)", ", CookingWithSwamiYogananda"], :img_url=>"http://bks0.books.google.pl/books?id=vktLMXSkWLQC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"More Healthy Homestyle Cooking", :authors=>["Evelyn Tribole"], :img_url=>"http://bks6.books.google.pl/books?id=vjR-FP4byZIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Heavenly Fragrance", :authors=>["Carol Selva Rajah"], :img_url=>"http://bks0.books.google.pl/books?id=NdisDpWxtnYC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Marwari Vegetarian Cooking", :authors=>["Sanjeev Kapoor", "Alyona Kapoor"], :img_url=>"http://bks9.books.google.pl/books?id=vHgAdnnnKzYC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking Free", :authors=>["Carol Fenster"], :img_url=>"http://bks8.books.google.pl/books?id=AWIYt7vJdiwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Steven Raichlen's Healthy Latin Cooking", :authors=>["Steven Raichlen"], :img_url=>"http://bks1.books.google.pl/books?id=FOJ1R9PcWKMC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking from the Garden", :authors=>["Ruth Lively"], :img_url=>"http://bks8.books.google.pl/books?id=pa65mjtEKfIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Fine Cooking Comfort Food", :authors=>["Fine Cooking Magazine Editors"], :img_url=>"http://bks2.books.google.pl/books?id=i_i7boHy4bgC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking on the Move", :authors=>["Andrea Prickett", "Bill Classon"], :img_url=>"http://bks9.books.google.pl/books?id=3IOUeg0QN4AC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Book of Spanish Cooking", :authors=>["Hilaire Walden"], :img_url=>"http://bks5.books.google.pl/books?id=fFvQqgJSQHgC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cookin' with Coolio", :authors=>["Coolio"], :img_url=>"http://bks4.books.google.pl/books?id=gg0AYyb659cC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with Green Tea", :authors=>["Ying Chang Compestine"], :img_url=>"http://bks0.books.google.pl/books?id=Jfcw74Y6E_cC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Backcountry Cooking", :authors=>["Dorcas S. Miller"], :img_url=>"http://bks0.books.google.pl/books?id=MXqh0TtOacUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"More Back Country Cooking", :authors=>["Dorcas Miller"], :img_url=>"http://bks3.books.google.pl/books?id=98LKkei12DwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking Outside the Pizza Box", :authors=>["Jean Patterson", "Danae Campbell"], :img_url=>"http://bks2.books.google.pl/books?id=Vnhid6RUKkUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Vegan Rustic Cooking", :authors=>["Diana White"], :img_url=>"http://bks2.books.google.pl/books?id=5o1fn4DHTToC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Book of Chinese Cooking", :authors=>["Jasper Spencer-Smith"], :img_url=>"http://bks7.books.google.pl/books?id=kUxqvzaDDWIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking the Japanese Way", :authors=>["Reiko Weston"], :img_url=>"http://bks9.books.google.pl/books?id=VIYXSTBlgLoC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Sanjeev Kapoor's Party Cooking", :authors=>["Sanjeev Kapoor", "Alyona Kapoor"], :img_url=>"http://bks7.books.google.pl/books?id=EA7dhw5zZsUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Elizabeth Baird's Classic Canadian Cooking", :authors=>["Elizabeth Baird"], :img_url=>"http://bks6.books.google.pl/books?id=7tis8xHm7q0C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Karibu", :authors=>["Ann Gardner"], :img_url=>"http://bks0.books.google.pl/books?id=1RMejBpIx88C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Kitchen Mysteries", :authors=>["Hervé This"], :img_url=>"http://bks0.books.google.pl/books?id=QB14rlPgSFUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Best of Polish Cooking", :authors=>["Karen West"], :img_url=>"http://bks9.books.google.pl/books?id=AALg5Mgs60EC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Healthy Cooking", :authors=>["Murdoch Books Staff"], :img_url=>"http://bks7.books.google.pl/books?id=fbqe8qYHAI4C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Classic Cooking Of Punjab", :authors=>["Jiggs Kalra", "Pushpesh Pant"], :img_url=>"http://bks0.books.google.pl/books?id=HHrUDlo0DfEC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking and Change", :authors=>["Paul McEvoy"], :img_url=>"http://bks4.books.google.pl/books?id=hbfmnm-now0C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Secrets of Fat-Free Cooking", :authors=>["Sandra Woodruff"], :img_url=>"http://bks7.books.google.pl/books?id=hXP6WUnI9GwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Technology of Extrusion Cooking", :authors=>["N.D. Frame"], :img_url=>"http://bks8.books.google.pl/books?id=w6SrO7EI0gMC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Slow Cooking", :authors=>["Joanne Glynn"], :img_url=>"http://bks8.books.google.pl/books?id=tEGjfXShcgwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Extrusion Cooking", :authors=>["Robin Guy"], :img_url=>"http://bks2.books.google.pl/books?id=nSIccsDAqVIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Tandoori Cooking @ Home", :authors=>["Kapoor", "Sanjeev"], :img_url=>"http://bks7.books.google.pl/books?id=s62bJPtQCGUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Commercial Cooking", :authors=>["Dolores Palladino"], :img_url=>"http://bks5.books.google.pl/books?id=ko4yjT0sljwC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Cooking from the Hip", :authors=>["Cat Cora"], :img_url=>"http://bks7.books.google.pl/books?id=RgqwWLcgnqAC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Fine Cooking Annual", :authors=>["Fine Cooking Magazine"], :img_url=>"http://bks1.books.google.pl/books?id=zEDK2US62osC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Mastering the Art of French Cooking", :authors=>["Julia Child"], :img_url=>"http://bks6.books.google.pl/books?id=yZ6TyW-X7R8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Catching Fire", :authors=>["Richard Wrangham"], :img_url=>"http://bks3.books.google.pl/books?id=-avfYyMouJEC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"German Cooking Today", :authors=>["Dr. Oetker "], :img_url=>"http://bks8.books.google.pl/books?id=dt8CjMt9-9IC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with Seitan", :authors=>["Leonard Jacobs"], :img_url=>"http://bks0.books.google.pl/books?id=m4XPdU4g4lkC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Thai Cooking from the Siam Cuisine Restaurant", :authors=>["Kwanruan Aksomboon", "Somchai Aksomboon"], :img_url=>"http://bks7.books.google.pl/books?id=xnpuu96dcI4C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Appalachian Home Cooking", :authors=>["Mark Sohn"], :img_url=>"http://bks6.books.google.pl/books?id=WlILLLWIBzoC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Italian cooking... what passion!", :authors=>["ATS Italia Editrice Srl"], :img_url=>"http://bks9.books.google.pl/books?id=tnQySistaJAC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"American Indian Cooking", :authors=>["Carolyn Niethammer"], :img_url=>"http://bks0.books.google.pl/books?id=0tDiMBUJdboC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with Merlot", :authors=>["Barbara Ray", "Norm Ray"], :img_url=>"http://bks1.books.google.pl/books?id=hjUZqZJIWIQC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Bill Neal's Southern Cooking", :authors=>["Bill Neal"], :img_url=>"http://bks3.books.google.pl/books?id=69Tw0dO-IkgC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Secrets of Hearty Turkish Home Cooking", :authors=>["Murat Yegul"], :img_url=>"http://bks6.books.google.pl/books?id=Rpax4hPuPmkC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking Desserts", :authors=>["Murdoch Books Staff"], :img_url=>"http://bks6.books.google.pl/books?id=CAb38kMYJZYC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with Jack", :authors=>["Lynne Tolley", "Mindy Merrell"], :img_url=>"http://bks8.books.google.pl/books?id=Pzd8szVZ8VwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Solar Cooking for Home and Camp", :authors=>["Linda Frederick Yaffe"], :img_url=>"http://bks0.books.google.pl/books?id=ko3sEYQUe3UC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Colonial Virginia's Cooking Dynasty", :authors=>["Katharine E. Harbury"], :img_url=>"http://bks2.books.google.pl/books?id=RAGQt70ViKkC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Classic Indian Cooking", :authors=>["Julie Sahni"], :img_url=>"http://bks3.books.google.pl/books?id=wC-xrLWouSIC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Manly Meals and Mom's Home Cooking", :authors=>["Jessamyn Neuhaus"], :img_url=>"http://bks9.books.google.pl/books?id=9thF2pjw5hgC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Kadai Cooking", :authors=>["Sanjeev Kapoor"], :img_url=>"http://bks8.books.google.pl/books?id=iT90ggKvNMkC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with Cajun Women", :authors=>["Nicole Denée Fontenot", "Alicia Fontenot Vidrine"], :img_url=>"http://bks1.books.google.pl/books?id=Om3QsrjT4bQC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Allergy Cooking with Ease", :authors=>["Nicolette M. Dumke"], :img_url=>"http://bks3.books.google.pl/books?id=dNICFKvE7UMC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Acquired Taste", :authors=>["T. Sarah Peterson"], :img_url=>"http://bks9.books.google.pl/books?id=B9d4rcnXnYUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Secrets of New England Cooking", :authors=>["Ella Shannon Bowles", "Dorothy S. Towle"], :img_url=>"http://bks6.books.google.pl/books?id=MJX3C0q1w74C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Secrets of Fat-Free Chinese Cooking", :authors=>["Ying Chang Compestine"], :img_url=>"http://bks4.books.google.pl/books?id=JkvU40t0IVoC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Classical Southern Cooking", :authors=>["Damon Fowler"], :img_url=>"http://bks3.books.google.pl/books?id=wTUDM_FK2TgC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"College Cooking", :authors=>["Megan Carle", "Jill Carle"], :img_url=>"http://bks6.books.google.pl/books?id=UwYJsklz7WkC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking Basics For Dummies", :authors=>["Bryan Miller", "Marie Rama"], :img_url=>"http://bks7.books.google.pl/books?id=VAUjPGX4_ckC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking the Whole Foods Way", :authors=>["Christina Pirello"], :img_url=>"http://bks1.books.google.pl/books?id=O1xTPmcoWNUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Food and Cooking in Victorian England", :authors=>["Andrea Broomfield"], :img_url=>"http://bks4.books.google.pl/books?id=fJ_JDp9OgJEC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Civil War Cooking", :authors=>["Susan Dosier"], :img_url=>"http://bks6.books.google.pl/books?id=4_UlaxCZpRUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking of the Maharajas", :authors=>["Shivaji Rao Holkar", "Shalini Devi Holkar"], :img_url=>"http://bks1.books.google.pl/books?id=1dDgAAAAMAAJ&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Cooking Under the Influence", :authors=>["Ben Canaider", "Greg Duncan Powell"], :img_url=>"http://bks0.books.google.pl/books?id=Kn0e7MsAx6IC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Food on the Frontier", :authors=>["Marjorie Kreidberg"], :img_url=>"http://bks6.books.google.pl/books?id=O0Gha-zzU5oC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Jamaican Cooking Made Easy", :authors=>["Getjamaica.Com"], :img_url=>"http://bks5.books.google.pl/books?id=q5e2fog12HwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Complete Guide to Healthy Cooking and Nutrition for College Students", :authors=>["J. Lucy Boyd"], :img_url=>"http://bks6.books.google.pl/books?id=6UhJmmv9q2QC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Basque Cooking and Lore", :authors=>["Darcy Williamson"], :img_url=>"http://bks6.books.google.pl/books?id=uwppGT0a86IC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Creative Quantity Cooking", :authors=>["Nell J. McCormack"], :img_url=>"http://bks6.books.google.pl/books?id=8oMD4_l5DFgC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Giant Book of Tofu Cooking", :authors=>["K. Lee Evans", "Chris Rankin"], :img_url=>"http://bks8.books.google.pl/books?id=l5stIE900QcC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Madhur Jaffrey's Quick & Easy Indian Cooking", :authors=>["Madhur Jaffrey"], :img_url=>"http://bks7.books.google.pl/books?id=42bkqsHlsNYC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Neighboring on the Air", :authors=>["Evelyn M. Birkby"], :img_url=>"http://bks9.books.google.pl/books?id=dzr9hGR_57cC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Vietnamese Home Cooking", :authors=>["Charles Phan"], :img_url=>"http://bks2.books.google.pl/books?id=z8EyMO5JIKkC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"French Provincial Cooking", :authors=>["Elizabeth David"], :img_url=>"http://bks7.books.google.pl/books?id=5PbUYzYe-xMC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Jiggs Kalra`s Classic Cooking Of Avadh", :authors=>["Kaira Jiggs"], :img_url=>"http://bks7.books.google.pl/books?id=7qWghKDC5NoC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking in Other WomenÕs Kitchens: Domestic Workers in the South,1865-1960", :authors=>["Sharpless, Rebecca"], :img_url=>"http://bks7.books.google.pl/books?id=I6538lRUJZIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with The Master Chef", :authors=>["Michel Roux Jr."], :img_url=>"http://bks8.books.google.pl/books?id=GA8rdZBrDAIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Techniques of Healthy Cooking, Professional Edition", :authors=>["Culinary Institute of America"], :img_url=>"http://bks8.books.google.pl/books?id=KDa4ZB_gvWgC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"More Home Cooking", :authors=>["Laurie Colwin"], :img_url=>"http://bks1.books.google.pl/books?id=I-zam5U7YpsC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"A Taste of Persia", :authors=>["Najmieh Batmanglij"], :img_url=>"http://bks6.books.google.pl/books?id=19C3DnJyWE0C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking on the Lewis and Clark Expedition", :authors=>["Mary Gunderson"], :img_url=>"http://bks6.books.google.pl/books?id=8cz4Cm0mAasC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Indian Cooking", :authors=>["Meenakshi Agarwal"], :img_url=>"http://bks8.books.google.pl/books?id=QvzR6gzqUgoC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Good Cooking", :authors=>["Jill Dupleix"], :img_url=>"http://bks5.books.google.pl/books?id=wxXHd8w7CDkC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking Healthy with a Microwave", :authors=>["JoAnna M. Lund"], :img_url=>"http://bks2.books.google.pl/books?id=ewxnxHoj5qAC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking Up U.S. History", :authors=>["Suzanne I. Barchers", "Patricia C. Marden"], :img_url=>"http://bks7.books.google.pl/books?id=lIT-h-M3DagC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with My Indian Mother-in-law", :authors=>["Simon Daley"], :img_url=>"http://bks1.books.google.pl/books?id=YCBJgtUM5qAC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Cooking Without Fuss", :authors=>["Jonny Haughton"], :img_url=>"http://bks8.books.google.pl/books?id=gNh2KASPRkEC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Byron", :authors=>["Steven Snow"], :img_url=>"http://bks3.books.google.pl/books?id=Sejo72GYqqQC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cibo", :authors=>["Michael Ponzio"], :img_url=>"http://bks0.books.google.pl/books?id=ty5PGdhtWuMC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Book of Vietnamese Cooking", :authors=>["Deh-Ta Hsiung"], :img_url=>"http://bks8.books.google.pl/books?id=M8fLAEoxInsC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking Without", :authors=>["Barbara Cousins"], :img_url=>"http://bks2.books.google.pl/books?id=_7Gyuy_5NvgC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"The Wizard of Food's Encyclopedia of Kitchen & Cooking Secrets", :authors=>["Myles H. Bader"], :img_url=>"http://bks3.books.google.pl/books?id=I5FVn9EjHH0C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with Convection", :authors=>["Beatrice Ojakangas"], :img_url=>"http://bks6.books.google.pl/books?id=4A_n2ll7ax4C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Complete Nose to Tail", :authors=>["Fergus Henderson"], :img_url=>"http://bks1.books.google.pl/books?id=Mu5B8HnarwEC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Le Cordon Bleu's Complete Cooking Techniques", :authors=>["Le Cordon Bleu"], :img_url=>"http://bks6.books.google.pl/books?id=fVYpHm_uhmoC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"The Book of Mediterranean Cooking", :authors=>["Lesley Mackley"], :img_url=>"http://bks2.books.google.pl/books?id=s-okfuHZCdsC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Cookin' Cajun Cooking School Cookbook", :authors=>["Lisette Verlander Susan Murphy"], :img_url=>"http://bks7.books.google.pl/books?id=wSURgX0JqEsC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Marie Claire Cooking", :authors=>["Donna Hay"], :img_url=>"http://bks4.books.google.pl/books?id=MSbERuWsAUoC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Sweet Hands", :authors=>["Ramin Ganeshram"], :img_url=>"http://bks4.books.google.pl/books?id=zNA8RWWB3gwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Professional Cooking (Unbranded), College Version", :authors=>["Wayne Gisslen"], :img_url=>"http://bks6.books.google.pl/books?id=Livv5D5CO3YC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Home Cooking", :authors=>["Laurie Colwin"], :img_url=>"http://bks8.books.google.pl/books?id=10y90mc_BtUC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Cucina Piemontese", :authors=>["Maria Grazia Asselle", "Brian Yarvin"], :img_url=>"http://bks0.books.google.pl/books?id=N5u3ijr7-ecC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Mastering the Art of Chinese Cooking", :authors=>["Eileen Yin-Fei Lo"], :img_url=>"http://bks1.books.google.pl/books?id=PRdT8VxlCJYC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Vibration Cooking", :authors=>["Vertamae Smart-Grosvenor"], :img_url=>"http://bks8.books.google.pl/books?id=KX4u6rXRgiUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Ratio", :authors=>["Michael Ruhlman"], :img_url=>"http://bks8.books.google.pl/books?id=zGaRpi4YdIQC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Disney's Cooking with Mickey & Friends", :authors=>["Pat Baird"], :img_url=>"http://bks9.books.google.pl/books?id=Di6Ud3qyb4EC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Smoke & Spice", :authors=>["Cheryl Alters Jamison", "Bill Jamison"], :img_url=>"http://bks3.books.google.pl/books?id=kS4Lw2gZrhsC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Delilah's Everyday Soul", :authors=>["Delilah Winder", "Jennifer Lindner McGlinn"], :img_url=>"http://bks0.books.google.pl/books?id=lhyS9nigr00C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking Art", :authors=>["MaryAnn F. Kohl", "Jean Potter"], :img_url=>"http://bks7.books.google.pl/books?id=4HkT9NC-f90C&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Tropic Cooking", :authors=>["Joyce L. Young", "Joyce LaFray"], :img_url=>"http://bks8.books.google.pl/books?id=Wxnh7exE27IC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Madhur Jaffrey's World-of-the-East Vegetarian Cooking", :authors=>["Madhur Jaffrey"], :img_url=>"http://bks2.books.google.pl/books?id=Yy8-AQAAIAAJ&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"The Cooking of France", :authors=>["Matthew Locricchio"], :img_url=>"http://bks0.books.google.pl/books?id=RILi6G5UAl0C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Pleasures of Cooking for One", :authors=>["Judith Jones"], :img_url=>"http://bks2.books.google.pl/books?id=MJvhHsBEp08C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"America's Founding Food", :authors=>["Keith W. F. Stavely", "Kathleen Fitzgerald"], :img_url=>"http://bks1.books.google.pl/books?id=xGzF54OaJE4C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking - A Basic Repertoire", :authors=>["Tony Polombo"], :img_url=>"http://bks5.books.google.pl/books?id=m8gf1XQ-8AsC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Everyday Cape Malay Cooking", :authors=>["Zainab Lagardien"], :img_url=>"http://bks1.books.google.pl/books?id=KngauTcH7cUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"How to Cook a Turkey", :authors=>["Fine Cooking Magazine"], :img_url=>"http://bks0.books.google.pl/books?id=o4eQl8cCuTYC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking on A Stick", :authors=>["Linda White"], :img_url=>"http://bks6.books.google.pl/books?id=2StW2au-XdQC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking for People with Dementia", :authors=>["Claudia Menebroecker", "Joern Rebbe"], :img_url=>"http://bks3.books.google.pl/books?id=YrYrTo-_Ov0C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with friends", :authors=>["Amy Lyles Wilson"], :img_url=>"http://bks9.books.google.pl/books?id=iGntPl3icD8C&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Everyday Low Carb Cooking", :authors=>["Alex Haas"], :img_url=>"http://bks2.books.google.pl/books?id=gSR3P9qYpNoC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Japanese Homestyle Cooking", :authors=>["Tokiko Suzuki"], :img_url=>"http://bks6.books.google.pl/books?id=yvueOPYfnXIC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Pork slaughtering, cutting, preserving, and cooking on the farm", :authors=>["United States. Science and Education Administration"], :img_url=>"http://bks2.books.google.pl/books?id=JRlJSYTMjqkC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking in Ancient Civilizations", :authors=>["Cathy K. Kaufman"], :img_url=>"http://bks0.books.google.pl/books?id=IFiIg7elnwIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking for Madam", :authors=>["Marta Sgubin", "Nancy Nicholas"], :img_url=>"http://bks5.books.google.pl/books?id=IlMpIBcWsEEC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"The Foods of the Greek Islands", :authors=>["Aglaia Kremezi"], :img_url=>"http://bks9.books.google.pl/books?id=I0qY3tUSBP0C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"White Trash Cooking: 25th Anniversary Edition", :authors=>["Ernest Matthew Mickler"], :img_url=>"http://bks4.books.google.pl/books?id=SzaeduhU2AEC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Best of Croatian Cooking", :authors=>["Liliana Pavicic", "Gordana Pirker-Mosher"], :img_url=>"http://bks4.books.google.pl/books?id=-W2XYRYORFcC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Culinary Reactions", :authors=>["Simon Quellen Field"], :img_url=>"http://bks0.books.google.pl/books?id=ub5-k97EnKkC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking in Cast Iron", :authors=>["Mara Reid Rogers"], :img_url=>"http://bks7.books.google.pl/books?id=kmjgf2jZiiwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Art of Wood-Fired Cooking", :authors=>["Andrea Mugnaini"], :img_url=>"http://bks4.books.google.pl/books?id=bP22ew153TYC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Television cooking shows", :authors=>["Lori F. Brost"], :img_url=>"http://bks3.books.google.pl/books?id=sVEeAQAAMAAJ&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Microwave Cooking for One", :authors=>["Marie T. Smith"], :img_url=>"http://bks1.books.google.pl/books?id=tVyBFQ7lAbIC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Biba's Northern Italian Cooking", :authors=>["Biba Caggiano"], :img_url=>"http://bks9.books.google.pl/books?id=zdkNv16vJd4C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Wood-Fired Cooking", :authors=>["Mary Karlin"], :img_url=>"http://bks5.books.google.pl/books?id=WHfAr3wfTHQC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking with Edible Flowers", :authors=>["Miriam Jacobs"], :img_url=>"http://bks7.books.google.pl/books?id=r6jcXCgYM5YC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Middle Eastern Cooking", :authors=>["Tess Mallos"], :img_url=>"http://bks3.books.google.pl/books?id=c0BFo2UYw10C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Summer Cooking", :authors=>["Elizabeth David"], :img_url=>"http://bks3.books.google.pl/books?id=rjm_stfGEaoC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Cooking The U.P. Way", :authors=>["Niru Gupta"], :img_url=>"http://bks3.books.google.pl/books?id=mat8BqswjX8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Elements of Cooking", :authors=>["Michael Ruhlman"], :img_url=>"http://bks9.books.google.pl/books?id=iX55tiQfXIgC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Meaning of Cooking", :authors=>["Jean-Claude Kaufmann"], :img_url=>"http://bks6.books.google.pl/books?id=k-j5Gf-oK3QC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Gordon Ramsay's Ultimate Home Cooking", :authors=>["Gordon Ramsay"], :img_url=>"http://bks3.books.google.pl/books?id=bKlx9OprVEUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Between Field and Cooking Pot", :authors=>["Florence E. Babb"], :img_url=>"http://bks0.books.google.pl/books?id=JWVhVLplfboC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Salt Block Cooking", :authors=>["Mark Bitterman", "Andrew Schloss"], :img_url=>"http://bks1.books.google.pl/books?id=f0LD6P5ReQwC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Hungarian cooking", :authors=>["Ruth Kershner"], :img_url=>"http://bks9.books.google.pl/books?id=ShUCwXvq60AC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Royal Hyderabadi Cooking", :authors=>["Sanjeev Kapoor"], :img_url=>"http://bks1.books.google.pl/books?id=pFivPqq7FbIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Knack Chinese Cooking", :authors=>["Belinda Hulin", "Kian Lam Kho", "Liesa Cole"], :img_url=>"http://bks4.books.google.pl/books?id=EwQKBndLHNkC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Classic Cooking Of Rajasthan, 1/e", :authors=>["Kalra", "Jiggs"], :img_url=>"http://bks1.books.google.pl/books?id=KAoqdFI9g3EC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Dione Lucas Gourmet Cooking School cookbook", :authors=>["Dione Lucas"], :img_url=>"http://bks2.books.google.pl/books?id=iSuMAU66ZtMC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"The Art of Polish Cooking", :authors=>["Alina Żerańska"], :img_url=>"http://bks7.books.google.pl/books?id=98Rt1mGgDUMC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Just Married and Cooking", :authors=>["Brooke Parkhurst", "James Briscione"], :img_url=>"http://bks3.books.google.pl/books?id=3lesJGAa9JIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Chinese Cooking For Dummies", :authors=>["Martin Yan"], :img_url=>"http://bks7.books.google.pl/books?id=hg3N89GDciQC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking the German Way", :authors=>["Helga Parnell"], :img_url=>"http://bks1.books.google.pl/books?id=qtBz6n6U-m0C&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Language, Social Structure, and Culture", :authors=>["Patricia Mayes"], :img_url=>"http://bks6.books.google.pl/books?id=JH_DDRaOlmIC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Go Home, Cook Rice", :authors=>["Joan Namkoong"], :img_url=>"http://bks8.books.google.pl/books?id=J_hLCCASdv0C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Wolfgang Puck's Modern French Cooking for the American Kitchen", :authors=>["Wolfgang Puck"], :img_url=>"http://bks5.books.google.pl/books?id=bCDR8qClrKkC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"College Vegetarian Cooking", :authors=>["Megan Carle", "Jill Carle"], :img_url=>"http://bks9.books.google.pl/books?id=LS4qmfKcZZoC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Cooking Down East", :authors=>["Marjorie Standish"], :img_url=>"http://bks1.books.google.pl/books?id=-324idq7AZUC&printsec=frontcover&img=1&zoom=4&source=gbs_api"},
    {:title=>"Santa Fe School of Cooking CookbookPb", :authors=>["Susan Curtis"], :img_url=>"http://bks6.books.google.pl/books?id=RsmLW89zp9wC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Hasty Pudding, Johnnycakes, and Other Good Stuff", :authors=>["Loretta Frances Ichord"], :img_url=>"http://bks0.books.google.pl/books?id=uCRdqi4lvK8C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Sensational Snacks", :authors=>["Barbara Beery"], :img_url=>"http://bks4.books.google.pl/books?id=uukpIfb5aCUC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"Basic Macrobiotic Cooking", :authors=>["Julia Ferré"], :img_url=>"http://bks3.books.google.pl/books?id=EdFSpYUNCFMC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Country Cooking of Ireland", :authors=>["Colman Andrews"], :img_url=>"http://bks2.books.google.pl/books?id=nKBdBblqiX0C&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"},
    {:title=>"The Tante Marie's Cooking School Cookbook", :authors=>["Mary S. Risley"], :img_url=>"http://bks4.books.google.pl/books?id=dy35FUDcl2oC&printsec=frontcover&img=1&zoom=4&edge=curl&source=gbs_api"}
  ])

Book.all.each do |book|
  book.state = Book::STATES.sample
  book.save
end
